title: Zijin Yu (于子金) # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master Candidate in Social Policy/Data Analytics (STEM)
  <br><br>
  @University of Pennsylvania 
  <br><br>
  <a href="https://www.linkedin.com/in/zijin-yu-486473126/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

